In [ ]:
import numpy as np

patterns = [
    np.array([+1, -1, +1, -1, +1, -1, +1, -1, +1, -1]),
    np.array([-1, +1, -1, +1, -1, +1, -1, +1, -1, +1]),
]

num_neurons = len(patterns[0])
weights = np.zeros((num_neurons, num_neurons))

for p in patterns:
    weights += np.outer(p, p)
np.fill_diagonal(weights, 0)

def recall(input_pattern, max_iters=10):
    state = np.copy(input_pattern)
    for _ in range(max_iters):
        for i in range(num_neurons):
            net_input = np.dot(weights[i], state)
            state[i] = +1 if net_input > 0 else -1
    return state

input_pattern = np.array([+1, -1, +1, +1, +1, -1, +1, -1, +1, -1])
output_pattern = recall(input_pattern)

print("Input Pattern:  ", input_pattern)
print("Recalled Pattern:", output_pattern)

Input Pattern:   [ 1 -1  1  1  1 -1  1 -1  1 -1]
Recalled Pattern: [ 1 -1  1 -1  1 -1  1 -1  1 -1]


In [ ]:
import numpy as np

def train_hopfield(patterns):
    """Train Hopfield network using Hebbian learning."""
    num_neurons = len(patterns[0])
    weights = np.zeros((num_neurons, num_neurons))
    for p in patterns:
        weights += np.outer(p, p)
    np.fill_diagonal(weights, 0)  
    return weights

def recall(weights, input_pattern, max_iters=10):
    """Recall a pattern from the Hopfield network."""
    state = np.copy(input_pattern)
    for _ in range(max_iters):
        for i in range(len(input_pattern)):
            net_input = np.dot(weights[i], state)
            state[i] = +1 if net_input > 0 else -1
    return state

def generate_patterns(num_patterns, num_neurons):
    """Generate random binary patterns."""
    return [np.random.choice([+1, -1], size=num_neurons) for _ in range(num_patterns)]

num_neurons = 10
accurate_recall = []
for num_patterns in range(1, 10):  
    patterns = generate_patterns(num_patterns, num_neurons)
    weights = train_hopfield(patterns)

    successful_recalls = 0
    for p in patterns:
        recalled = recall(weights, p)
        if np.array_equal(recalled, p):
            successful_recalls += 1
    
    recall_accuracy = successful_recalls / len(patterns)
    accurate_recall.append((num_patterns, recall_accuracy))

for num_patterns, accuracy in accurate_recall:
    print(f"Stored Patterns: {num_patterns}, Recall Accuracy: {accuracy:.2f}")


Stored Patterns: 1, Recall Accuracy: 1.00
Stored Patterns: 2, Recall Accuracy: 1.00
Stored Patterns: 3, Recall Accuracy: 1.00
Stored Patterns: 4, Recall Accuracy: 0.75
Stored Patterns: 5, Recall Accuracy: 0.40
Stored Patterns: 6, Recall Accuracy: 0.67
Stored Patterns: 7, Recall Accuracy: 0.29
Stored Patterns: 8, Recall Accuracy: 0.25
Stored Patterns: 9, Recall Accuracy: 0.56


In [ ]:
import numpy as np
import random

def train_hopfield(patterns):
    num_neurons
    num_neurons = len(patterns[0])
    weights = np.zeros((num_neurons, num_neurons))
    for p in patterns:
        weights += np.outer(p, p)
    np.fill_diagonal(weights, 0)
    return weights

def recall(weights, input_pattern, max_iters=10):
    """Recall a pattern from the Hopfield network."""
    state = np.copy(input_pattern)
    for _ in range(max_iters):
        for i in range(len(input_pattern)):
            net_input = np.dot(weights[i], state)
            state[i] = +1 if net_input > 0 else -1
    return state

def flip_bits(pattern, num_flips):
    """Introduce errors by flipping random bits in the pattern."""
    flipped_pattern = np.copy(pattern)
    flip_indices = random.sample(range(len(pattern)), num_flips)
    for idx in flip_indices:
        flipped_pattern[idx] *= -1  
    return flipped_pattern

num_neurons = 10
patterns = [np.random.choice([+1, -1], size=num_neurons) for _ in range(1)]  # Train with 1 pattern
weights = train_hopfield(patterns)

original_pattern = patterns[0]
max_flips = num_neurons 
results = []

for num_flips in range(max_flips + 1):
    noisy_pattern = flip_bits(original_pattern, num_flips)
    recalled_pattern = recall(weights, noisy_pattern)
    success = np.array_equal(recalled_pattern, original_pattern)
    results.append((num_flips, success))

print("Bit-Flips | Recall Success")
for num_flips, success in results:
    print(f"    {num_flips}      |      {success}")


Bit-Flips | Recall Success
    0      |      True
    1      |      True
    2      |      True
    3      |      True
    4      |      True
    5      |      True
    6      |      False
    7      |      False
    8      |      False
    9      |      False
    10      |      False


In [ ]:
import numpy as np

def initialize_board(size):
    return np.random.choice([0, 1], size=(size, size))

def energy_function(board):
    row_constraints = np.sum(board, axis=1) - 1
    col_constraints = np.sum(board, axis=0) - 1
    energy = np.sum(row_constraints ** 2) + np.sum(col_constraints ** 2)
    return energy

def update_board(board):
    size = board.shape[0]
    for _ in range(100):
        for i in range(size):
            for j in range(size):
                board[i, j] = 1 - board[i, j]
                new_energy = energy_function(board)
                if new_energy > energy_function(board):
                    board[i, j] = 1 - board[i, j]
    return board

def is_valid_solution(board):
    rows_valid = all(np.sum(board, axis=1) == 1)
    cols_valid = all(np.sum(board, axis=0) == 1)
    return rows_valid and cols_valid

size = 8
board = initialize_board(size)

print("Initial Energy:", energy_function(board))
board = update_board(board)
print("Final Energy:", energy_function(board))
print("Valid Solution:", is_valid_solution(board))

print("Final Board Configuration:")
print(board)


Initial Energy: 236
Final Energy: 236
Valid Solution: False
Final Board Configuration:
[[0 0 0 0 0 0 1 1]
 [1 1 0 1 1 0 1 1]
 [1 1 0 1 1 1 0 0]
 [0 0 0 0 0 1 1 1]
 [1 1 0 1 1 1 1 0]
 [1 1 1 1 1 0 0 0]
 [1 0 1 0 1 1 1 0]
 [1 1 0 1 0 0 1 1]]


In [ ]:
import numpy as np

num_cities = 10
distances = np.random.randint(1, 100, size=(num_cities, num_cities))
np.fill_diagonal(distances, 0)

A, B, C = 500, 500, 1
max_iters = 100

def energy_function(X, distances):
    row_constraints = np.sum(X, axis=1) - 1
    col_constraints = np.sum(X, axis=0) - 1
    constraint_term = A * np.sum(row_constraints ** 2) + B * np.sum(col_constraints ** 2)
    distance_term = 0
    for i in range(num_cities):
        for j in range(num_cities):
            for k in range(num_cities):
                if j != k:
                    distance_term += C * distances[i, j] * X[i, j] * X[i, k]
    return constraint_term + distance_term

def update_network(X, distances):
    for _ in range(max_iters):
        for i in range(num_cities):
            for j in range(num_cities):
                X[i, j] = 1 - X[i, j]
                new_energy = energy_function(X, distances)
                if new_energy > energy_function(X, distances):
                    X[i, j] = 1 - X[i, j]
    return X

def is_valid_tsp_solution(X):
    rows_valid = all(np.sum(X, axis=1) == 1)
    cols_valid = all(np.sum(X, axis=0) == 1)
    return rows_valid and cols_valid

X = np.random.choice([0, 1], size=(num_cities, num_cities))

print("Initial Energy:", energy_function(X, distances))
X = update_network(X, distances)
print("Final Energy:", energy_function(X, distances))
print("Valid Solution:", is_valid_tsp_solution(X))

route = np.argmax(X, axis=1)
print("Route:", route)


Initial Energy: 257574
Final Energy: 257574
Valid Solution: False
Route: [0 0 2 0 1 0 1 1 0 0]
